version: '3'

services:
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api-1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=r2dbc:postgresql://postgres-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
    networks:
      - app-network
  api-2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api-2
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=r2dbc:postgresql://postgres-db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
    networks:
      - app-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
  postgres-db:
    image: postgres:latest
    container_name: rinha-backend-db
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '120MB'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    networks:
      - app-network
networks:
  app-network: