version: '3'

services:
  api-1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api-1
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
    networks:
      - app-network
#  api-2:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    hostname: api-2
#    networks:
#      - app-network
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - api-1
#      - api-2
#    ports:
#      - "9999:9999"
#    networks:
#      - app-network
  postgres-db:
    image: postgres:latest
    container_name: rinha-backend-db
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5433"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
networks:
  app-network:
